### ISSUE TITLE
data_scraping.R issues with Soldier R.S. snotel missing data

### ISSUE THREAD

**Issue by acmoody** [kendrakaiser/WRWC#2]
Fails on loop in `data_scraping.R` at line 239  with i == 8 (Soldier SNOTEL)

```R
today_swe[i] <-
snotel_data_out$snow_water_equivalent[snotel_data_out$site_name == snotel_site_info$site_name[i] & 
snotel_data_out$date == max(snotel_data_out$date)]
```

The conditionals used for subsetting the data don't overlap because Soldier R.S. does not have data for the max snotel date, March 10th 2021 in this case. Because of this, updating the today_swe dataframe fails.

**Comment by kendrakaiser** [comment]
fixed! It now selects the prior dates swe since 'todays' date isn't updated until midnight.
